feat: add php8.2 image
owncloud-ci/php pull request #164
Opened 2023-09-18 12:41 UTC by DeepDiver1975

2023-09-18 13:00 UTC, DeepDiver1975 commented
images php7.0-php7.3 are not building

2023-09-18 15:36 UTC, phil-davis commented
Looks like some old-version PHP has "gone away" in conjunction with whatever Ubuntu we are trying to install it on...

We should be able to just remove all that. We do not need PHP 7.3 or earlier in any CI any more.

And I think that if we remove the old PHP build pipelines, the existing docker images for those versions will remain being published as-they-are. Is that correct @xoxys ?

2023-09-18 17:26 UTC, DeepDiver1975 commented
moved this to a dedicated issue  unrelated to this pr.

2023-09-18 17:27 UTC, DeepDiver1975 commented
approval and merge is welcome to unblock my core pr - thx

2023-09-19 06:59 UTC, xoxys requested changes
Some files need to be renamed to 8.2:

![image](https://github.com/owncloud-ci/php/assets/3391958/1d5c66be-7650-4489-9515-865566a3b942)

2023-09-19 06:59 UTC, xoxys commented on v8.2/manifest.tmpl
> +image: owncloudci/php:8.1
Still `8.1`

2023-09-19 07:14 UTC, xoxys approved these changes

2023-09-19 07:15 UTC, merged

2023-09-19 07:21 UTC, DeepDiver1975 commented
THX